service_name: '8d43459a-6395-45fd-80c6-b7c0722ebc4e'

http:
  url: http://0.0.0.0:9000
  cors:
    access_control_allow_headers:
      - Content-Type
      - Cache-Control
      - Authorization
      - X-Total-Count
    access_control_allow_origin:
      - https://go2.uiscom.ru

uc_flow_node:
  register_on_start: false
  execute_view_queue_size: 500
  execute_view_workers: 5
  private_url: https://c340-178-169-86-75.ngrok.io
  public_url: https://c340-178-169-86-75.ngrok.io
  uc_flow:
    domain: https://uc-flow-v2-pp-api.comagic.ru
    jwt_secret: 9109a79d-74f9-45bd-b369-5e7a885421e5s
